### ISSUE TITLE
Working configuration example

### ISSUE THREAD

**Issue by simmel** [ryarnyah/collectd-prometheus#2]
Hey!

Thanks for creating this, looks awesome!

I've been struggling to get it working the last couple of hours. I can't get it to change the default config.

This is the config I've been using:
```
LoadPlugin python
<Plugin python>
    ModulePath "/local/collectd/prom/lib/python2.7/site-packages"
    Import "collectd-prometheus"
    <Module "collectd-prometheus">
       Interval 5
       Protocol https
       SslIgnore True
       Port 2379
    </Module>
</Plugin>
```

```
systemd[1]: Starting Statistics collection and monitoring daemon...
[…]
collectd[29004]: plugin_load: plugin "python" successfully loaded.
collectd[29004]: Systemd detected, trying to signal readyness.
collectd[29004]: Initialization complete, entering read-loop.
```

and then nothing. Other metrics collected are sent fine, but not the prometheus-scraped ones.

I noticed that if I added the config:
```
       Process anythingreally
```

it started up but only using the default settings.

What am I doing wrong?

Thanks!

**Comment by ryarnyah** [comment]
Hey!

You need to have a `<Process>` child in your `<Module>` declaration, can you try this? It's design this way so you can monitor multiple process @see https://github.com/ryarnyah/collectd-prometheus/blob/master/collectd-prometheus.py#L85
```
LoadPlugin python
<Plugin python>
    ModulePath "/local/collectd/prom/lib/python2.7/site-packages"
    Import "collectd-prometheus"
    <Module "collectd-prometheus">
      Interval 5
      <Process>
         Process "{{ process.name }}"
         Protocol "https"
         SslIgnore True
         Port 2379
     </Process>
   </Module>
</Plugin>
```

**Comment by simmel** [comment]
Thank you! That worked!

I hope it's OK that I create a few PRs to improve the documentation?

**Comment by ryarnyah** [comment]
> Thank you! That worked!
> 
> I hope it's OK that I create a few PRs to improve the documentation?

With pleasure!
